spring:
  application:
    name: jenkins-demo
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
  
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'